name: C/C++ CI

on:
  pull_request:

jobs:
  Checks_changing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with make
      run: |
          git fetch origin trunk:refs/remotes/origin/trunk
          [[ -z "${GITHUB_BASE_REF}" ]] && BRANCH_VAR=HEAD~1 || BRANCH_VAR=origin/trunk
          echo "${BRANCH_VAR}"
          echo "$(git diff --name-only ${BRANCH_VAR})"
          LIST_CHECK_FILES=$(git diff --name-only ${BRANCH_VAR} | grep --color=never '.cpp\|.tpp' | tr '\n' ' ')
          if [[ -n ${LIST_CHECK_FILES} ]]
          then
            python3 tools/run_project.py --run_type=build --files=${LIST_CHECK_FILES}
          else
            echo "Nothing to build"
          fi
    - name: Run tests
      run: |
          git fetch origin trunk:refs/remotes/origin/trunk
          [[ -z "${GITHUB_BASE_REF}" ]] && BRANCH_VAR=HEAD~1 || BRANCH_VAR=origin/trunk
          echo "${BRANCH_VAR}"
          echo "$(git diff --name-only ${BRANCH_VAR})"
          LIST_CHECK_FILES=$(git diff --name-only ${BRANCH_VAR} | grep --color=never '.cpp\|.tpp' | tr '\n' ' ')
          if [[ -n ${LIST_CHECK_FILES} ]]
          then
            python3 tools/run_project.py --run_type=tests --files=${LIST_CHECK_FILES}
          else
            echo "Nothing to test"
          fi
    # - name: Run clang-tidy
    #   run: |
    #       git fetch origin trunk:refs/remotes/origin/trunk
    #       [[ -z "${GITHUB_BASE_REF}" ]] && BRANCH_VAR=HEAD~1 || BRANCH_VAR=origin/trunk
    #       echo "${BRANCH_VAR}"
    #       echo "$(git diff --name-only ${BRANCH_VAR})"
    #       LIST_CHECK_FILES=$(git diff --name-only ${BRANCH_VAR} | grep --color=never '.cpp' | tr '\n' ' ')
    #       if [[ -n ${LIST_CHECK_FILES} ]]
    #       then
    #         sudo apt install -y clang-tidy-14
    #         python3 tools/run_clang_tidy.py -clang-tidy-binary clang-tidy-14 -q ${LIST_CHECK_FILES}
    #       else
    #         echo "Nothing check in clang-tidy"
    #       fi

        


